# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

jobs:
- job: Test
  container:
    image: "linuxbrew/brew"
  steps:
  - script: |
      sudo apt-get update -qq
      sudo apt-get install -qq automake
    displayName: Install C++ modules
  - script: |
      cd releases/links_v2.0/
      git submodule init
      git submodule update
      ./autogen.sh
      ./configure
      make
    displayName: Compile LINKS
  - script: |
      mkdir CI_TEST && cd CI_TEST
      pwd
      sudo apt-get install -qq wget
      wget http://www.bcgsc.ca/downloads/supplementary/LINKS/K12_full2dONT_longread.fa
      wget http://www.bcgsc.ca/downloads/supplementary/LINKS/ecoliK12_abyss_illumina_contig_baseline.fa
      echo K12_full2dONT_longread.fa > K12_F2D.fof
      ../LINKS-make LINKS draft=ecoliK12_abyss_illumina_contig_baseline.fa readsFof=K12_F2D.fof b=CI_TEST
      cd ../
      ls
      pwd
    displayName: Run basic test
