# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

jobs:
- job: Test
  container:
    image: "linuxbrew/brew"
  steps:
  - script: |
      sudo apt-get update -qq
      sudo apt-get install -qq automake
    displayName: Install C++ modules
  - script: |
      cd releases/links_v2.0/
      ./autogen.sh
      ./configure
      make
    displayName: Compile LINKS
